import Head from "next/head";
import Categories from "../components/Categories";
import Location from "../components/Location";
import Cta from "../components/Cta";
import Footer from "../components/Footer";
import How from "../components/How";
import NavBar from "../components/NavBar";
import SideBars from "../components/SideBars";
import styles from "../styles/Home.module.css";

export default function Home() {
	const location = "Kai Plaza";
	const leftImage = "/img/mads-schmidt-rasmussen-6YmzwamGzCg-unsplash 2.jpg";
	const rightImage = "/img/jumiafood-homepage-right-splash-services.jpg";

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavBar />
			<div className="hero">
				<SideBars image={leftImage} />
				<div className={styles.innerContainer}>
					<Location location={location} />
					<Categories />
				</div>
				<SideBars image={rightImage} />
			</div>
			<How />
			<Cta />
			<Footer />
		</div>
	);
}
